name: Hello World
author: Luka Ma
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Lule
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node16"
  main: "dist/index.js"
